<div class="bg-ocean"></div>
<div class="bg-magenta"></div>
<div class="bg-mist"></div>
<div class="bg-azure"></div>
<div class="max-w-[850px] max-w-[800px] max-w-[950px] mx-auto md:text-[28px] xl:text-[30px]"></div>
<div class="whitespace-nowrap"></div>
<div class="text-center text-left text-right sm:text-left sm:text-center sm:text-right"></div>
<div class="pl-4 sm:pl-8 md:pl-16 lg:pl-24 xl:pl-32"></div>
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5"></div>
<div class="md:grid-cols-1 md:grid-cols-2 md:grid-cols-3"></div>
<div class="sm:text-xl-2"></div>
